added 01858-Sello.php
ifatoki/hng-wonderwoman-task-1 pull request #106
Opened 2020-06-03 11:53 UTC by SelloFotoyi

Please alert me if I missed something, and thank you for the great work!

2020-06-03 13:47 UTC, ifatoki requested changes

2020-06-03 13:47 UTC, ifatoki commented on scripts/01858-Sello.php
> +	echo " using ".$language " for stage 2 task.";
Please append a space and your email behind the word `task` as described [here](https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700)

2020-06-03 20:59 UTC, McToluene requested changes
Please there should be only one output. Visit https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700 for the format

2020-06-04 00:49 UTC, melissaugrai approved these changes

2020-06-04 13:14 UTC, McToluene approved these changes

2020-06-06 17:08 UTC, closed without merging