Blossom first commit to HNG task 2
ifatoki/hng-wonderwoman-task-1 pull request #132
Opened 2020-06-03 13:00 UTC by blossom-babs

2020-06-03 14:34 UTC, ifatoki requested changes

2020-06-03 14:34 UTC, ifatoki commented on scripts/05511-Blossom.js
> +const myID = "05511";
Please include your full HNG ID here e.g `HNG-055111`

2020-06-03 14:51 UTC, blossom-babs commented on scripts/05511-Blossom.js
> +const myID = "05511";
Alright. Done. Anything else

2020-06-04 18:20 UTC, lindaokorie27 approved these changes

2020-06-05 03:00 UTC, melissaugrai approved these changes

2020-06-05 06:11 UTC, ifatoki requested changes

2020-06-05 06:11 UTC, ifatoki commented on scripts/05511-Blossom.js
> +Hello World, this is ${myFullName} with HNGi7 ID ${myID}, using ${languageUsed} for stage 2 task. ${emailAddress}
Please remove the `.` after the word `task` before your email address.

2020-06-05 09:38 UTC, ifatoki approved these changes

2020-06-05 09:39 UTC, merged