Complete task 1
ifatoki/hng-wonderwoman-task-1 pull request #136
Opened 2020-06-03 13:07 UTC by mercykip

Hey, This is Mercy Kipyegon's complete task one for wonder-woman team. Feel free to add a comment

2020-06-03 15:22 UTC, ifatoki requested changes

2020-06-03 15:22 UTC, ifatoki commented on scripts/HNG-01819-mercyk.php
> +$hello= "Hello world, this is ".$name.", Email ".$email." with HNGi7 ID ".$hngid. " using ".$language. " for stage 2 task, ";
Please the email should come last after the word `task` as highlighted [here](https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700)

2020-06-04 22:42 UTC, melissaugrai approved these changes

2020-06-04 22:46 UTC, melissaugrai approved these changes

2020-06-04 23:20 UTC, ifatoki approved these changes

2020-06-04 23:20 UTC, merged