adding samju200 script for stage 2
ifatoki/hng-wonderwoman-task-1 pull request #199
Opened 2020-06-03 18:15 UTC by Samju200

Yeah! I am Done with the task! I am now  adding my script.

2020-06-03 20:04 UTC, ifatoki requested changes
Please check this up as your changes aren't visible.

2020-06-03 20:41 UTC, Samju200 commented
i don't understand.
my program is not running or what

2020-06-03 21:10 UTC, lindaokorie27 approved these changes

2020-06-04 02:52 UTC, melissaugrai approved these changes

2020-06-04 06:24 UTC, melissaugrai approved these changes

2020-06-04 17:30 UTC, ifatoki approved these changes

2020-06-04 17:31 UTC, merged