HNG stage 2 task
ifatoki/hng-wonderwoman-task-1 pull request #251
Opened 2020-06-03 22:43 UTC by onebee9

Hiya, please let me know if there are any changes required.

2020-06-03 23:01 UTC, ifatoki requested changes
Please move your script into the `scripts/` folder.

2020-06-03 23:18 UTC, onebee9 commented
> Please move your script into the `scripts/` folder.

@ifatoki Should I create a new script folder, put the file in it, and then push? or just add my file to the scripts folder with all the other interns' files and THEN push? or delete the files in the folder, leaving only mine and push that? The expectation here isnt clear?

2020-06-04 14:27 UTC, ifatoki commented
> > Please move your script into the `scripts/` folder.
> 
> @ifatoki Should I create a new script folder, put the file in it, and then push? or just add my file to the scripts folder with all the other interns' files and THEN push? or delete the files in the folder, leaving only mine and push that? The expectation here isnt clear?

Simply copy your script into the existing `scripts` folder with the other interns scripts.

2020-06-04 15:19 UTC, ifatoki approved these changes

2020-06-04 15:19 UTC, merged