victory
ifatoki/hng-wonderwoman-task-1 pull request #28
Opened 2020-06-03 00:39 UTC by vickywane

Made my insertion following `motdde`'s example

2020-06-03 03:24 UTC, vickywane commented
The test file can be moved anywhere as long as the `__dirname` path is updated

2020-06-04 07:34 UTC, ifatoki requested changes
Please delete the `scripts.test.js` file. It is not required of you.

2020-06-04 23:28 UTC, vickywane commented
Alright

2020-06-05 00:56 UTC, melissaugrai approved these changes

2020-06-05 06:18 UTC, ifatoki approved these changes

2020-06-05 06:18 UTC, merged