task-1 completed
ifatoki/hng-wonderwoman-task-1 pull request #297
Opened 2020-06-04 10:16 UTC by Lnikhil-143

hello this task completed by nikhil under team wonderwoman on hing.

2020-06-04 11:53 UTC, McToluene requested changes
Please include email in your output. Check here for more info https://hngi7.slack.com/archives/C014G2TMQ3G/p1591260231242800

2020-06-05 03:29 UTC, Lnikhil-143 commented
done changes included email

2020-06-05 04:13 UTC, melissaugrai approved these changes

2020-06-05 05:06 UTC, vasanth9 approved these changes

2020-06-05 05:06 UTC, melissaugrai approved these changes

2020-06-05 05:18 UTC, McToluene approved these changes

2020-06-05 05:18 UTC, merged