okoroaforchristian
ifatoki/hng-wonderwoman-task-1 pull request #41
Opened 2020-06-03 05:35 UTC by okorochristen

this is Okoroafor Christian with HNGi7 ID 05244 using Python Programming language for  stage 2 task

2020-06-03 09:06 UTC, lindaokorie27 requested changes
Append HNG to your ID like so HNG-05244

2020-06-04 00:04 UTC, melissaugrai requested changes
Add email into output message,  after the word task, please

2020-06-04 22:11 UTC, lindaokorie27 reviewed
Please look at the sample string given and adjust

2020-06-04 22:45 UTC, ifatoki approved these changes

2020-06-04 22:46 UTC, merged