Create 01857-omowunmi.py
ifatoki/hng-wonderwoman-task-1 pull request #438
Opened 2020-06-04 22:21 UTC by faozziyyah

Here's my updated task, please add

2020-06-04 22:25 UTC, lindaokorie27 requested changes
Follow the specified format [here](https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700)

2020-06-04 22:28 UTC, sholance commented
According to the link posted, you should declare the variables (name, id, language, and email) before printing them in the output.

2020-06-05 04:12 UTC, melissaugrai approved these changes

2020-06-05 06:16 UTC, ifatoki approved these changes

2020-06-05 06:17 UTC, merged