Create 02227-KimayaUrdhwareshe
ifatoki/hng-wonderwoman-task-1 pull request #456
Opened 2020-06-04 23:18 UTC by wonderwoman23

Submission for task 2.

2020-06-04 23:30 UTC, melissaugrai requested changes
I believe you need to save this file .py,  also missing your email at the end after the word task

2020-06-04 23:30 UTC, tosinibrahim96 commented on scripts/02227-KimayaUrdhwareshe
> +print("Hello World, this is {0} with HNGi7 ID {1} using {2} for stage 2 task.".format(Name, ID, Language))
Please add your email address to this out. Here's a sample format `Hello World, this is Ciroma Adekunle with HNGi7 ID HNG-1010 using Javascript for stage 2 task abc@example.com`

2020-06-04 23:43 UTC, wonderwoman23 commented on scripts/02227-KimayaUrdhwareshe
> +
Email = "kimaya23@gmail.com"

2020-06-04 23:46 UTC, wonderwoman23 commented
Done! Thank you.

2020-06-05 00:58 UTC, melissaugrai approved these changes

2020-06-05 06:19 UTC, ifatoki approved these changes

2020-06-05 06:20 UTC, merged