this is my script for task 2 with slack username itsmaleeq
ifatoki/hng-wonderwoman-task-1 pull request #59
Opened 2020-06-03 08:07 UTC by CodeLeeq

my pull request

2020-06-03 09:23 UTC, lindaokorie27 requested changes
please use console.log instead

2020-06-03 18:09 UTC, CodeLeeq commented
> please use console.log instead

Done and my email is added

2020-06-04 07:39 UTC, ifatoki approved these changes

2020-06-04 07:39 UTC, merged

2020-06-04 09:04 UTC, CodeLeeq commented
thanks

Thanks & Regards.
*Babajide AbdulMaleek **Onayemi** | *Web Developer* |*
Mobile: *+2347025449200*





On Thu, Jun 4, 2020 at 8:40 AM ifatoki <notifications@github.com> wrote:

> Merged #59 <https://github.com/ifatoki/hng-wonderwoman-task-1/pull/59>
> into develop.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ifatoki/hng-wonderwoman-task-1/pull/59#event-3405509680>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI5C6NS4AZMFV3PAZTOEUQDRU5FVXANCNFSM4NRNUDSA>
> .
>