task done
ifatoki/hng-wonderwoman-task-1 pull request #84
Opened 2020-06-03 10:36 UTC by ojolanre

Task 1 contribution done

2020-06-03 11:37 UTC, lindaokorie27 requested changes
The console.log statement is enough. Please remove the return statement

2020-06-03 12:10 UTC, ojolanre commented
Done

2020-06-03 13:32 UTC, ifatoki requested changes

2020-06-03 13:32 UTC, ifatoki commented on scripts/02248-Olanre.js
> +	let task = `Hello World, this is ${fullName} with HNGi7 ID ${ID} using ${language} for stage 2 task`;
Please include your email after the word `task` and a space. Look [here](https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700) for details

2020-06-03 14:24 UTC, ojolanre commented
Please do check the one i just added, thanks

2020-06-04 08:03 UTC, lindaokorie27 approved these changes

2020-06-04 09:34 UTC, ifatoki approved these changes

2020-06-04 09:34 UTC, merged