add my script for the task
ifatoki/hng-wonderwoman-task-1 pull request #88
Opened 2020-06-03 10:55 UTC by virginiah894

2020-06-03 11:27 UTC, virginiah894 commented
Add email

2020-06-03 13:34 UTC, ifatoki submitted a review, later dismissed

2020-06-03 13:34 UTC, ifatoki commented on scripts/04021-virginiahperiah.py
>  print(f" Hello World, this is {full_name} with HNGi7 ID {hng_num} using {used_lang} for stage 2 task.")
Hi, you only added the email variable but we'd need you to print it after the word `task` and one space. You can find more info [here](https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700)

2020-06-03 15:52 UTC, virginiah894 commented
Add the email.

2020-06-03 20:41 UTC, McToluene requested changes
Please include HNG in your HNG-ID output. Check here for more info https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700

2020-06-03 21:00 UTC, virginiah894 commented
HI,
Done


On Wed, Jun 3, 2020 at 4:34 PM ifatoki <notifications@github.com> wrote:

> *@ifatoki* requested changes on this pull request.
> ------------------------------
>
> In scripts/04021-virginiahperiah.py
> <https://github.com/ifatoki/hng-wonderwoman-task-1/pull/88#discussion_r434569681>
> :
>
> > @@ -1,4 +1,5 @@
>  full_name = 'Virginiah Periah'
>  hng_num = '04021'
>  used_lang = 'Python'
> +email = 'virgyperry@gmail.com'
>  print(f" Hello World, this is {full_name} with HNGi7 ID {hng_num} using {used_lang} for stage 2 task.")
>
> Hi, you only added the email variable but we'd need you to print it after
> the word task and one space. You can find more info here
> <https://hngi7.slack.com/archives/C014G2TMQ3G/p1591185461011700>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ifatoki/hng-wonderwoman-task-1/pull/88#pullrequestreview-423556286>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM7L5OVTK2NKUQCC6ZJLQJTRUZGORANCNFSM4NRRU6YA>
> .
>

2020-06-03 21:02 UTC, virginiah894 commented
Fix HNg Id

2020-06-03 21:06 UTC, virginiah894 commented
fixed the HNG ID

2020-06-04 02:47 UTC, melissaugrai approved these changes

2020-06-05 14:37 UTC, onedebos submitted a review, later dismissed

2020-06-05 14:56 UTC, onedebos requested changes
You need to remove the space you have before "Hello". print(f" Hello World, this is {full_name} with HNGi7 ID {hng_num}  using {used_lang} for stage 2 task. {email}") => should be print(f"Hello World, this is {full_name} with HNGi7 ID {hng_num}  using {used_lang} for stage 2 task. {email}")

2020-06-05 15:42 UTC, virginiah894 commented
i have fixed the space

2020-06-06 13:05 UTC, virginiah894 commented
new pull request

2020-06-06 13:12 UTC, Mahalinoro approved these changes
Reviewed!

2020-06-06 13:55 UTC, onedebos approved these changes

2020-06-06 13:55 UTC, merged